=== GlaucoSouza/PetShopServiceList/petshop.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="petShopServices">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="service" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="petName"/>
              <xs:element type="xs:string" name="animalType"/>
              <xs:element type="xs:string" name="ownerName"/>
              <xs:element type="xs:int" name="ownerPhone"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

<!-- Generated my XSD in the website https://www.freeformatter.com/xsd-generator.html using my XML file. -->

=== GlaucoSouza/PetShopServiceList/petshop.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="petshop.xsl"?>

<petShopServices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="petshop.xsd"> 
    <service name="Grooming">
            <petName>Lulinha</petName>
            <animalType>Dog</animalType>
            <ownerName>Paulo</ownerName>
            <ownerPhone>0838884408</ownerPhone>
    </service>

    <service name="Vaccinate">
        <petName>Tirulipa</petName>
            <animalType>Dog</animalType>
            <ownerName>Johny</ownerName>
            <ownerPhone>0838847842</ownerPhone>
       
    </service>

    <service name="Castrate">
       
            <petName>Matuzal√©m</petName>
            <animalType>Dog</animalType>
            <ownerName>Fred</ownerName>
            <ownerPhone>0885859587</ownerPhone>
       
     </service>

    <service name="Blood Test + Chipping">
       
            <petName>Meleca</petName>
            <animalType>Cat</animalType>
            <ownerName>Lucia</ownerName>
            <ownerPhone>0838746592</ownerPhone>
      
    </service>

      <service name="Blood Test + Chipping">
       
            <petName>ABC</petName>
            <animalType>CDE</animalType>
            <ownerName>LMN</ownerName>
            <ownerPhone>0838746592</ownerPhone>
       
    </service>
</petShopServices>
